require("dotenv").config({ path: require("path").join(__dirname, "../.env") });
const mongoose = require("mongoose");
const SentEmail = require("../models/sentEmail.model");

const emailsList = [
  "talentacquisition@qf.org.qa",
  "careers@nmj-group.qa",
  "careers@cme.com.qa",
  "careers@codingsouls.com",
  "careers@beema.com.qa",
  "recruitment@invest.qa",
  "recruitment@barwa.com.qa",
  "recruitment@mosanada.qa",
  "recruitment@qafac.com.qa",
  "careers@turing-technology.co",
  "careers@kloudynet.com",
  "hr@synoteca.com",
  "career@mocean.com.my",
  "career@jos.com.my",
  "hr.my@tp-link.com",
  "career@ortech.com.my",
  "convene_recruitment@azeus.com",
  "job@rgtech.com.my",
  "admin@alphv.com",
  "careers@kafuapp.com",
  "careers@sn-tec.com",
  "careers@nourva.ai",
  "careers@rsna.com.sa",
  "careers@atss.sa",
  "careers@cignify.sa",
  "careers@dconcept.com.sa",
  "careers@nassolutions.sa",
  "careers@secedge.sa",
  "hr@global.com.sa",
  "careers@jiblatech.com",
  "careers@infiniteware.com",
  "info@utechkw.com",
  "hr@almerak.com",
  "hello@amlakalarabia.com",
  "careers@voxel.com.kw",
  "info@eemc.com",
  "info@kuwaittechnologies.com",
  "hello@bricks.com.kw",
  "careers@masirat.com",
  "careers@unitedtech.me",
  "hr@enums.co",
  "mercy@zionteck.com",
  "admin@zionteck.com",
  "info@bluelaketech.om",
  "info@sactech.co.om",
  "careers@alsiyabi.com",
  "careers@ominvest.com",
  "careers@lovosis.com",
  "recruiting@sbb.ch",
  "careers@sdataway.com",
  "recruiting@twint.ch",
  "jobs@bbtsoftware.ch",
  "contact@palambur.ch",
  "jobs@adnovum.com",
  "careers@embotech.com",
  "jobs@logicstar.ai",
  "info@ai-medical.ch",
  "hr@karakun.com",
  "careers@prontoid.com",
  "info@callista.ch",
  "careers@illizeo.com",
  "careers@swiftstrike.ai",
  "career@tillitis.se",
  "join@multiply.tech",
  "work@cloudbackend.com",
  "info@knowit.se",
  "careers@qtagg.com",
  "jobs@alicelabs.ai",
  "careers@devolens.com",
  "careers@hvnt.com",
  "careers@kdab.com",
  "work@kastelo.net",
  "careers@hyre.no",
  "post@deepclaw.no",
  "careers@skyetec.no",
  "jobb@kodeworks.no",
  "careers@avelor.dev",
  "talento@aicox.com",
  "hola@justnetsystems.com",
  "info@amurasystems.com",
  "cv@enigmia.es",
  "jobs@algotech.solutions",
  "contact@latrikos.com",
  "altech@altech.es",
  "careers@codverx.com",
  "hr@amk.solutions",
  "info@bitzandbytezsolutions.com",
  "careers@avionlabs.co",
  "careers@appdeck.com",
  "careers@starforcesolutions.com",
  "careers@oxigen.ca",
  "careers@enscalesystems.com",
  "careers@codazz.com",
  "careers@helpward.com",
  "careers@nextgenix.ca",
  "contact@signxsolutions.com",
  "info@wowa.ca",
  "job@britailabs.com",
  "careers@andabove.com",
  "careers@coaleypeak.co.uk",
  "careers@juxt.pro",
  "careers@elixirsoftware.co.uk",
  "careers@deliverance.ai",
  "info@codebased.co.uk",
  "careers@omnicodecreations.co.uk",
  "hr@saakuru.com",
  "career@deptechdigital.com",
  "karir@moveitation.id",
  "info@dgos.id",
  "career@rentalnesia.com",
  "careers@settyn.com",
  "contact@appstronaute.com",
  "recrutement@synchrone.fr",
  "recrutement-edf-master@edf.fr",
  "people.recruitment@manchester.ac.uk",
  "recruitmentservices.people@manchester.ac.uk",
  "hrservices@manchester.ac.uk",
  "solliciteren@coolblue.nl",
  "recruitment@eenvoud.nl",
  "werk@reactonline.nl",
  "jobs@tcs.de",
  "jobs@zlyde.com",
  "career@soundsuit.fm",
  "jobs@any2any.co",
  "kontakt@bytenative.de",
  "hr@ibi-systems.de",
  "jobs@firetail.io",
  "hello@ulvio.be",
  "arne@clubcubby.be",
  "jobs@waiterr.app",
  "career@decidio.cc",
  "careers@dectria.com",
  "careers@vollville.com",
  "hakemukset@mediasignal.fi",
  "careers@agileday.io",
  "info.tyrand@gmail.com",
  "job@x44.dk",
  "job@marotino.com",
  "jobs@acuru.com",
  "recruitment@energygroup.ie",
  "info@deployer.pt",
  "jobs@techrivo.com",
  "jobs@craftablesoftware.com",
  "jobs@hpm.ro",
  "internship@hpm.ro",
  "itnasbavi@ders.cz",
  "ders@ders.cz",
  "adam@gallico.cz",
  "kristi.kaur@mountbirch.com",
  "info@mountbirch.com",
  "personalhr@erply.com",
  "careers@salttechno.com",
  "info@e-bros.lt",
  "marius.zilinskas@e-bros.lt",
  "careers@sap.com",
  "career@deloitte.de",
  "recruitmentmaroc.ma@capgemini.com",
  "careers.inmorocco.ma@capgemini.com"
];

async function seedSentEmails() {
  try {
    if (!process.env.DATABASE_URL) {
      console.error("DATABASE_URL is missing in .env");
      process.exit(1);
    }
    await mongoose.connect(process.env.DATABASE_URL);
    console.log("Connected to MongoDB");

    // Extract unique clean emails
    const uniqueEmails = [...new Set(emailsList.map(e => e.trim().toLowerCase()))];

    const ops = uniqueEmails.map(email => ({
      updateOne: {
        filter: { email },
        update: { $setOnInsert: { email } },
        upsert: true
      }
    }));

    const result = await SentEmail.bulkWrite(ops);
    console.log(`Successfully seeded emails! Upserted: ${result.upsertedCount}, Matched: ${result.matchedCount}`);
    process.exit(0);
  } catch (error) {
    console.error("Error seeding sent emails:", error);
    process.exit(1);
  }
}

seedSentEmails();
